# Python NumPy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` and print the numpy version and the configuration (★☆☆)

`Hint: import … as` and `np.__version__, np.show_config)`

In [1]:
import numpy as np
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda3\\Library\\include']


#### 2. Convert a list of numeric value into a one-dimensional NumPy array (★☆☆)
`💡 hint: numpy.array`

In [4]:
a= np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(a)

[[9. 8. 7.]
 [6. 5. 4.]]


#### 3. Create a null vector of size 9 (★☆☆)
`💡 hint: np.zeros`

In [6]:
temp = np.zeros(9)
print(temp)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)
`💡 hint: size, itemsize`

In [12]:
Z = np.zeros((5,4))
print(Z.size)
print(Z.itemsize)
print("%d bytes" % (Z.size * Z.itemsize))

20
8
160 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`💡hint: np.info`

In [15]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 12 but the sixth value which is 1 (★☆☆)
`💡hint: array[12]`

In [16]:
temp = np.zeros(10)
temp[5] = 1
print(temp)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 20 to 59 (★☆☆)
`💡hint: arange`

In [17]:
temp = np.arange(20,59)
print(temp)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58]


#### 8. Reverse a vector (first element becomes last) (★☆☆)
`💡hint: array[::-1]`

In [18]:
temp = np.arange(20,59)
temp = temp[::-1]
print(temp)

[58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35
 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20]


#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`

In [26]:
#法一：
temp = np.arange(12,21)
temp = temp.reshape(3,3)
print(temp)
#法二：
temp = np.arange(12,21).reshape(3,3)
print(temp)

[[12 13 14]
 [15 16 17]
 [18 19 20]]
[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`

In [27]:
temp = np.nonzero([3,7,0,0,9,0])
print(temp)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [3]:
import numpy as np
A = np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

In [4]:
A = np.random.random((3,3,3))
print(A)

[[[0.88379833 0.92661489 0.08297539]
  [0.21319236 0.52925215 0.90752133]
  [0.46985242 0.20223336 0.85059323]]

 [[0.03010435 0.40620285 0.70270853]
  [0.13699191 0.28463663 0.361108  ]
  [0.20350228 0.53278035 0.89335557]]

 [[0.79378783 0.0915685  0.28744761]
  [0.22988523 0.80824762 0.15560569]
  [0.68770328 0.04746391 0.65231035]]]


#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [5]:
import numpy as np
temp = np.random.random((9,9))
print(temp)
max=np.max(temp,axis=0)
min=np.min(temp,axis=1)
print(max,min)

[[0.41397825 0.55597981 0.16207619 0.67370945 0.37590578 0.13991672
  0.71334705 0.35375578 0.78763044]
 [0.6410795  0.89521866 0.91470822 0.49777953 0.1780842  0.77473731
  0.9770503  0.21200946 0.97070716]
 [0.96176266 0.37882464 0.19738128 0.69518829 0.62338116 0.87615978
  0.29938509 0.85614718 0.84379104]
 [0.35353753 0.49654074 0.87358075 0.49228259 0.80237989 0.88432745
  0.1031724  0.38788905 0.60652516]
 [0.88343608 0.0986526  0.23398212 0.74671583 0.49439353 0.21049719
  0.30564269 0.28200557 0.8483483 ]
 [0.53433922 0.50375028 0.13164089 0.06754686 0.41875647 0.71670788
  0.20096159 0.91476983 0.65510455]
 [0.63134301 0.51212003 0.66346207 0.97535378 0.44567899 0.83341642
  0.46255058 0.71212147 0.23458988]
 [0.60059394 0.96244122 0.97799951 0.22048314 0.97144009 0.96300265
  0.13791179 0.1832428  0.08546593]
 [0.8705122  0.49794708 0.51242667 0.95013533 0.8934199  0.13706188
  0.71075313 0.52687154 0.4117189 ]]
[0.96176266 0.96244122 0.97799951 0.97535378 0.97144009 0.96300

#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [14]:
A = np.random.random(20)
print(A)
m = A.mean()
print(m)

[0.184525   0.41840993 0.57640423 0.30484465 0.92977111 0.97330073
 0.66483398 0.85768503 0.44024439 0.89047006 0.38114114 0.82242676
 0.83250254 0.6446475  0.02719464 0.21317614 0.27301753 0.00705305
 0.54358415 0.11479762]
0.5050015084467037


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [5]:
# 方法一
import numpy as np
A= np.zeros([10,10])
A[0,:],A[-1,:],A[:,0],A[:,-1] = 1,1,1,1
print(A)
# 方法二
B = np.ones((10,10))
B[1:-1,1:-1] = 0
print(B)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [10]:
A = np.ones((5,5))
A = np.pad(A, pad_width=1, mode='constant', constant_values=0)
print(A)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

In [11]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`

In [12]:
A = np.diag(1+np.arange(5),k=-1)
print(A)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [14]:
A = np.zeros((6,6),dtype=int)
A[1::2,::2] = 1#从第一行，到最后一行，中间间隔两行；中间间隔两列
A[::2,1::2] = 1
print(A)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [21]:
print(np.unravel_index(100,(8,9,10)))

(1, 1, 0)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`💡hint: np.tile`

In [23]:
temp = np.array([[0,1],[1,0]])
print(temp)
A = np.tile(temp, (8,8))#将数组沿着X轴Y轴都扩大8倍
print(A)

B = np.tile(np.array([[0,1],[1,0]]),(8,8))    
print(B)

[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 

#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`

In [25]:
temp = np.random.random((5,5))
print(temp)
#np.std()：计算全局标准差
A = (temp-np.mean(temp))/np.std(temp)
print(A)

[[0.12162433 0.53908888 0.20537971 0.50176136 0.97011421]
 [0.58366341 0.20725358 0.92669256 0.50992877 0.46244104]
 [0.6627252  0.1829648  0.90122972 0.78081289 0.27942447]
 [0.89622719 0.33353791 0.98676206 0.29129584 0.83520472]
 [0.28906212 0.16789376 0.95895811 0.16240395 0.54968322]]
[[-1.39126953  0.02318729 -1.10748886 -0.10328612  1.48359087]
 [ 0.17421508 -1.10113977  1.33646925 -0.07561321 -0.23651155]
 [ 0.44209291 -1.18343523  1.25019585  0.84219856 -0.85660979]
 [ 1.23324623 -0.67326218  1.53999722 -0.81638712  1.0264894 ]
 [-0.8239554  -1.23449905  1.44579168 -1.25309965  0.05908314]]


#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [6]:
print(np.dot(np.random.random((6,3)),np.random.random((3,4))))
print(np.ones((6,3)) @ np.ones((3,4)))

[[1.13671947 0.85768089 0.91902529 1.73177443]
 [1.06373666 0.80001844 0.93450469 1.38381377]
 [0.26546905 0.33054023 0.19760511 0.45549336]
 [0.8975037  0.71751201 0.80202548 1.12344805]
 [0.44003007 0.20954529 0.40147944 0.52789753]
 [0.88796691 0.82900314 0.68323583 1.45930659]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [28]:
# Author: Evgeni Burovski
A = np.arange(11)
A[(3 < A) & (A < 8)] *= -1
print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [30]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b 
[False False]
a >= b 
[False False] 
a < b 
[ True True] 
a <= b 
[ True True]
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

In [33]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-33-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-33-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [34]:
A = np.random.uniform(-10,+10,10)
print(A)
print(np.copysign(np.ceil(np.abs(A)), A))
print(np.where(A>0, np.ceil(A), np.floor(A)))

[-6.31893475 -4.98043352 -5.22924972  6.36667368 -9.33992023  1.89286465
 -9.40580698 -7.91190688  8.43878805  3.28654644]
[ -7.  -5.  -6.   7. -10.   2. -10.  -8.   9.   4.]
[ -7.  -5.  -6.   7. -10.   2. -10.  -8.   9.   4.]


#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [40]:
A1 = np.random.randint(0,10,10)
A2 = np.random.randint(0,10,10)
print(A1,A2)
print(np.intersect1d(A1,A2))

[9 8 4 7 9 1 3 8 8 7] [2 3 5 0 7 5 0 9 5 7]
[3 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`💡hint: np.seterr, np.errstate`

In [38]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`💡hint: imaginary number`

In [39]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


<ipython-input-39-c6ff0ad7fd7b>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`💡hint: np.datetime64, np.timedelta64`

In [42]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday,today,tomorrow)

2022-04-29 2022-04-30 2022-05-01


#### 34. How to get all the dates corresponding to the month of January 2016? (★★☆)
`💡hint: np.arange(dtype=datetime64['D'])`

In [44]:
A = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(A)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

In [45]:
A = np.ones(3)*1
B = np.ones(3)*2
print(A,B)
np.add(A,B,out=B)
print(A,B)
np.divide(A,2,out=A)
print(A,B)
np.negative(A,out=A)
print(A,B)
np.multiply(A,B,out=A)
print(A,B)

[1. 1. 1.] [2. 2. 2.]
[1. 1. 1.] [3. 3. 3.]
[0.5 0.5 0.5] [3. 3. 3.]
[-0.5 -0.5 -0.5] [3. 3. 3.]
[-1.5 -1.5 -1.5] [3. 3. 3.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`💡hint: %, np.floor, astype, np.trunc`

In [46]:
A = np.random.uniform(0,10,10)

print(A - A%1)
print(A // 1)
print(np.floor(A))
print(A.astype(int))
print(np.trunc(A))

[7. 8. 1. 4. 6. 2. 1. 2. 7. 1.]
[7. 8. 1. 4. 6. 2. 1. 2. 7. 1.]
[7. 8. 1. 4. 6. 2. 1. 2. 7. 1.]
[7 8 1 4 6 2 1 2 7 1]
[7. 8. 1. 4. 6. 2. 1. 2. 7. 1.]


#### 37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)
`💡hint: np.arange`

In [9]:
a = np.tile(np.arange(0, 3), (3,3))
print(a)

[[0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]]


#### 38. Consider a generator function that generates 9 integers and use it to build an array (★☆☆)
`💡hint: np.fromiter`

In [2]:
import numpy as np
def generate():
    for x in range(9):
        yield x
A = np.fromiter(generate(),dtype=float,count=-1)
print(A)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


In [5]:
def generator():
    while True:
        yield (np.random.randint(10))   
n = 0;N = []
for g in generator():
    N.append(g)
    n += 1
    if n == 10:
        break
print(N)

[6, 8, 6, 3, 7, 5, 4, 0, 8, 7]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`💡hint: np.linspace`

In [3]:
A = np.linspace(0,1,11,endpoint=False)[1:]
print(A)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)
`💡hint: sort`

In [8]:
temp = np.random.random(10)
print(temp)
temp = np.sort(temp)
print(temp)

[0.00430014 0.1867694  0.19026182 0.15647893 0.88725144 0.53954876
 0.18815387 0.03399092 0.6232169  0.71037856]
[0.00430014 0.03399092 0.15647893 0.1867694  0.18815387 0.19026182
 0.53954876 0.6232169  0.71037856 0.88725144]


#### 41. How to sum a small array faster than np.sum? (★★☆)
`💡hint: np.add.reduce`

In [9]:
A = np.arange(10)
np.add.reduce(A)
print(A)

[0 1 2 3 4 5 6 7 8 9]


#### 42. Consider two random array A and B, check if they are equal (★★☆)
`💡hint: np.allclose, np.array_equal`

In [15]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)
`💡hint: flags.writeable`

In [16]:
A = np.zeros(10)
A.flags.writeable = False
A[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`💡hint: np.sqrt, np.arctan2`

In [21]:
a=np.random.randint(0,10,5)
print(a)
c=np.argmax(a)a[c]=0
print(a)

[9 7 1 0 2]
[0 7 1 0 2]


#### 45. Create random vector of size 5 and replace the maximum value by 0 (★★☆)
`💡hint: argmax`

In [30]:
A = np.random.random(10)
A[A.argmax()] = 0
print(A)

[0.3530047  0.18642132 0.079655   0.82738717 0.         0.44203398
 0.24089959 0.17052359 0.3320956  0.66835552]


In [35]:
A = np.random.randint(0,10,10)
A_max_index = np.argmax(A)                
A[A_max_index] = 0
print(A)
A = np.random.random(10)
A[A.argmax()] = 0                        
print(A)

[1 5 6 8 1 8 7 0 8 5]
[0.17179403 0.22591029 0.19199035 0.23255344 0.         0.13072539
 0.15244045 0.31859773 0.8474287  0.46570356]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`💡hint: np.meshgrid`

In [38]:
A= np.zeros((5,5), [('x',float),('y',float)])
A['x'], A['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(A)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`💡hint: np.subtract.outer`

In [43]:
X = np.arange(10)
Y = X + 0.6
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

34620.61342506313


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`💡hint: np.iinfo, np.finfo, eps`

In [44]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)
`💡hint: np.set_printoptions`

In [46]:
np.set_printoptions(threshold=float("inf"))
A = np.zeros((5,5))
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`💡hint: argmin`

In [50]:
A = np.arange(50)
M = np.random.uniform(0,50)
index = (np.abs(A-M)).argmin()
print(A[index])

17


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`💡hint: dtype`

In [55]:
A = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(A)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-55-b5e407d4dd4e>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  A = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`💡hint: np.atleast_2d, T, np.sqrt`

In [56]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.92038286 1.03884928 0.77551311 0.47871083 1.05343683
  0.56442167 0.66388441 0.96314411 0.6253299 ]
 [0.92038286 0.         0.50364586 0.76489948 0.86017206 0.48843202
  0.6294026  0.26158959 0.54752004 0.30913032]
 [1.03884928 0.50364586 0.         0.4541552  0.7284998  0.02909815
  0.50612279 0.52167647 0.11174725 0.64700234]
 [0.77551311 0.76489948 0.4541552  0.         0.33563679 0.4820475
  0.24374935 0.60567377 0.34245921 0.70983132]
 [0.47871083 0.86017206 0.7284998  0.33563679 0.         0.75211315
  0.24366309 0.62387656 0.62534388 0.67859863]
 [1.05343683 0.48843202 0.02909815 0.4820475  0.75211315 0.
  0.52681219 0.52073611 0.13999665 0.64502405]
 [0.56442167 0.6294026  0.50612279 0.24374935 0.24366309 0.52681219
  0.         0.41518292 0.41346366 0.4981814 ]
 [0.66388441 0.26158959 0.52167647 0.60567377 0.62387656 0.52073611
  0.41518292 0.         0.51007118 0.12655442]
 [0.96314411 0.54752004 0.11174725 0.34245921 0.62534388 0.13999665
  0.41346366 0.510071

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
`💡hint: view and [:] =`

In [58]:
A = (np.random.rand(10)*100).astype(np.float32)
Y = A.view(np.int32)
Y[:] =A
print(Y)

[78 58 76 89 64  6  3 67 73 32]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint: np.genfromtxt`

In [61]:
from io import StringIO
A = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
B = np.genfromtxt(A, delimiter=",", dtype=np.int)
print(B)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-61-798c023739ce>:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  B = np.genfromtxt(A, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`💡hint: np.ndenumerate, np.ndindex`

In [65]:
A=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(A):
    print(index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)
`💡hint: np.meshgrid, np.exp`

#### 57. How to randomly place e elements in a 2D array? (★★☆)
`💡hint: np.put, np.random.choice`

#### 58. Subtract the mean of each row of a matrix (★★☆)
`💡hint: mean(axis=,keepdims=)`

#### 59. How to sort an array by the nth column? (★★☆)
`💡hint: argsort`

#### 60. How to tell if a given 2D array has null columns? (★★☆)
`💡hint: any, ~`

#### 61. Find the nearest value from a given value in an array (★★☆)
`💡hint: np.abs, argmin, flat`

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`💡

#### 63. Create an array class that has a name attribute (★★☆)
`💡hint: class method`

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`💡hint: np.bincount | np.add.at`

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`💡hint: np.bincount`

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`💡hint: np.unique`

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`💡hint: sum(axis=(-2,-1))`

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`💡hint: np.bincount`

#### 69. How to get the diagonal of a dot product? (★★★)
`💡hint: np.diag`

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`💡hint: array[::4]`

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
`💡hint: array[:, :, None]`

#### 72. How to swap two rows of an array? (★★★)
`💡hint: array[[]] = array[[]]`

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`💡hint: repeat, np.roll, np.sort, view, np.unique`

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`💡hint: np.repeat`

#### 75. How to compute averages using a sliding window over an array? (★★★)
`💡hint: np.cumsum`

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`💡hint: from numpy.lib import stride_tricks`

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`💡hint: np.logical_not, np.negative`

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`💡hint: minimum maximum`

#### 81. Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`💡hint: stride_tricks.as_strided`

#### 82. Compute a matrix rank (★★★)
`💡hint: np.linalg.svd`

#### 83. How to find the most frequent value in an array?
`💡hint: np.bincount, argmax`

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`💡hint: stride_tricks.as_strided`

#### 85. Create a 2D array subclass such that a[i,j] == a[j,i] (★★★)
`💡hint: class method`

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`💡hint: np.tensordot`

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`💡hint: np.add.reduceat`

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)
`💡hint: np.argsort | np.argpartition`

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`💡hint: np.indices`

#### 91. How to create a record array from a regular array? (★★★)
`💡hint: np.core.records.fromarrays`

#### 92. Consider a large vector A, compute A to the power of 3 using 3 different methods (★★★)
`💡hint: np.power, *, np.einsum`

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`💡hint: np.where`

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
`💡hint: np.unpackbits`

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
`💡hint: np.ascontiguousarray | np.unique`

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`💡hint: np.einsum`

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`💡hint: np.cumsum, np.interp`

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`💡hint: np.logical_and.reduce, np.mod`

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`💡hint: np.percentile`